apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ph-ee-connector-mpesa
  title: PH M-Pesa Connector
  description: Zeebe connector integrating with the Safaricom M-Pesa API for mobile money payments and loan repayments
  annotations:
    github.com/project-slug: one-acre-fund/ph-ee-connector-mpesa
    backstage.io/kubernetes-id: ph-ee-connector-mpesa
    sonarqube.org/project-key: one-acre-fund_ph-ee-connector-mpesa
    backstage.io/code-coverage: sonarqube
  tags:
    - java
    - zeebe-connector
    - payment-hub
    - paymenthub
    - mpesa
    - safaricom
    - mno
    - mobile-money
  links:
    - url: https://sonarcloud.io/summary/new_code?id=one-acre-fund_ph-ee-connector-mpesa
      title: Code Quality Dashboard
      icon: dashboard
    - url: https://ph-web.oneacrefund.org
      title: Production Environment
      icon: globe
spec:
  type: worker
  lifecycle: production
  owner: group:one-acre-fund/team-credit-and-payments
  system: connectors
  consumesApis:
    - zeebe-gateway-grpc-api
  dependsOn:
    - resource:default/zeebe-cluster
